blank_issues_enabled: false
contact_links:
  - name: How to create a Minimal & Reproducible example
    url: https://stackoverflow.com/help/minimal-reproducible-example
    about: Good reproduction are key to a good bug report.
